apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-yen
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-yen
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        name: hello-yen
    spec:
      containers:
      - name: hello-yen
        image: gcr.io/devops-epitech/hello:4ef4549aa5d0cd7d3e85b16f2b345857cc9163e8
        ports:
        - containerPort: 8000
        - containerPort: 8080
        resources:
          requests:
              cpu: 10m

---
apiVersion: v1
kind: Service
metadata:
  name: hello-yen
  labels:
     name: hello-yen
spec:
  type: LoadBalancer
  selector:
    name: hello-yen
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
