apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-quentin
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-quentin
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        name: hello-quentin
    spec:
      containers:
      - name: hello
        image: gcr.io/devops-epitech/hello@sha256:e9d53bdce031f3089552f4fd95af8eaf608d09448d026f78b829309ce83254ed
        ports:
        - containerPort: 8000
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-quentin
  labels:
     name: hello-quentin
spec:
  type: LoadBalancer
  selector:
    name: hello-quentin
  ports:
    - protocol: TCP
      name: flask
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: prometheus
      port: 8080
      targetPort: 8080
