apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kevin
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-kevin
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        name: hello-kevin
    spec:
      containers:
      - name: hello-kevin
        image: gcr.io/devops-epitech/hello:3b90cb03376f119387413e7dec5beb72bacf412d
        ports:
        - containerPort: 8000
        - containerPort: 8080
        resources:
          requests:
              cpu: 10m

---
apiVersion: v1
kind: Service
metadata:
  name: hello-kevin
  labels:
     name: hello-kevin
spec:
  type: LoadBalancer
  selector:
    name: hello-kevin
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
