apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-anna
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-anna
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        name: hello-anna
    spec:
      containers:
      - name: hello-anna
        image: gcr.io/devops-epitech/hello:477a9b198bc0b94bbdff048b561f0f97ec5aa263
        ports:
        - containerPort: 8000
        - containerPort: 8080
        resources:
          requests:
              cpu: 10m

---
apiVersion: v1
kind: Service
metadata:
  name: hello-anna
  labels:
     name: hello-anna
spec:
  type: LoadBalancer
  selector:
    name: hello-anna
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
