apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kc
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hello-kc
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        name: hello-kc
    spec:
      containers:
      - name: hello-kc
        image: gcr.io/devops-epitech/hello:8774c49007f9937c90b1aca90bda2486fc46706e
        ports:
        - containerPort: 8000
        - containerPort: 8080
        resources:
          requests:
              cpu: 10m

---
apiVersion: v1
kind: Service
metadata:
  name: hello-kc
  labels:
     name: hello-kc
spec:
  type: LoadBalancer
  selector:
    name: hello-kc
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
