version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: prometheus_multiproc_dir=/tmp pytest hello.py
      - run: docker build -t hello:$CIRCLE_SHA1 .
