version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            prometheus_multiproc_dir=/tmp pytest hello.py
      - run: docker build -t hello:$CIRCLE_SHA1 .
