version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: run tests
          command: |
            prometheus_multiproc_dir=/tmp pipenv run pytest hello.py

      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t hello:$CIRCLE_SHA1 .
